import Head from "next/head";
import Home from "./home/index.page";

import HomeContext, { HomeContextProps } from "../pages/home/context";

export async function getStaticProps() {
  const resCharacterList = await fetch(
    "https://rickandmortyapi.com/api/character"
  );
  const characterList = await resCharacterList.json();

  const resEpisodeList = await fetch("https://rickandmortyapi.com/api/episode");
  const episodeList = await resEpisodeList.json();

  const resLocationList = await fetch(
    "https://rickandmortyapi.com/api/location"
  );
  const locationList = await resLocationList.json();

  return {
    props: {
      characterList,
      episodeList,
      locationList,
    },
  };
}

export default function Index({
  characterList,
  episodeList,
  locationList,
}: HomeContextProps) {
  return (
    <HomeContext.Provider value={{ characterList, episodeList, locationList }}>
      <Head>
        <title>Rick and Morty Wiki</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
    </HomeContext.Provider>
  );
}
